/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/identify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plant.id proxy with fingerprint cache (blueprint §8.2, §9.1) */
        post: operations["identifyPlant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open-Meteo proxy with per-location 3h cache */
        get: operations["getWeather"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/share/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a care-share invite (S-5/S-6, FCM notify on accept) */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        IdentifyRequest: {
            /** @description sha256 of downscaled image bytes */
            imageFingerprint: string;
            /** @description downscaled WebP/AVIF ≤150KB */
            base64?: string;
            latitude?: number;
            longitude?: number;
        };
        IdentifyResponse: {
            /** @description true when served from the Firestore fingerprint cache */
            cached?: boolean;
            /** @description Top Plant.id classification suggestions, highest confidence first */
            species?: {
                scientificName: string;
                /** @description 0..1 Plant.id probability */
                confidence?: number;
            }[];
            /** @description Plant.id's confidence that the photo actually shows a plant */
            isPlant?: {
                probability?: number;
            };
            isHealthy?: {
                probability?: number;
                binary?: boolean;
            };
            /** @description Top disease suggestion when Plant.id ran health analysis */
            disease?: {
                name?: string;
                probability?: number;
            };
        };
        WeatherPayload: {
            tempC: number;
            rh: number;
            uvIndex: number;
            cloudCover: number;
            daylightHours: number;
            precipitationMm: number;
            /** Format: date-time */
            fetchedAt?: string;
        };
        InviteRequest: {
            plantId: string;
            /** Format: email */
            inviteeEmail: string;
            /** @enum {string} */
            role: "owner" | "caregiver" | "viewer";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    identifyPlant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentifyRequest"];
            };
        };
        responses: {
            /** @description Identification result (from cache or fresh Plant.id call) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentifyResponse"];
                };
            };
            /** @description Invalid body, or no image sent on a cache miss */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Daily Plant.id budget exhausted — client should fall back to TFLite/PlantNet/manual */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No PLANT_ID_API_KEY configured on the server */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getWeather: {
        parameters: {
            query: {
                lat: number;
                lon: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cached weather payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherPayload"];
                };
            };
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteRequest"];
            };
        };
        responses: {
            /** @description Invite created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
